image: node:22-bullseye

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm ci
    - npx gulp build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
